### PR TITLE
Fix URL_PREFIX not existing if using the server settings

### PR DESCRIPTION
**Pull request by ghickman**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
@ghickman Do you mind rebasing these 3 commits? Then I'll gladly pull it in. Thanks.

**Comment by ghickman** [comment]
@mattrobenolt Done =)

**Comment by mattrobenolt** [comment]
Thank you, sir.

**Comment by ghickman** [comment]
:cake:

**Comment by mattrobenolt** [comment]
I pushed a 0.1.1 to PyPi.

**Comment by ghickman** [comment]
Cheers!

**Pull request merged**
