### PR TITLE
Switch URL_PREFIX for SENTRY_URL_PREFIX

### PR DESCRIPTION
**Pull request by ghickman**
In the case where URL_PREFIX doesn't exist, use SENTRY_URL_PREFIX in
it's place since this should be defined in the user's local settings.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
In what case would URL_PREFIX not exist? I took that logic out of the actual email module. I haven't seen SENTRY_URL_PREFIX.

**Comment by ghickman** [comment]
URL_PREFIX is defined as an empty string here: https://github.com/dcramer/sentry/blob/3.8.2/sentry/conf/defaults.py#L41

However I found it was turning up as None a lot of the time. I never actually tracked down where this was getting changed as I knew the SENTRY_URL_PREFIX was set in my config. I figured that as it's part of the generated config file and mentioned in the docs (http://sentry.readthedocs.org/en/latest/quickstart/index.html#initializing-the-configuration) it was safe to rely on this.

**Comment by mattrobenolt** [comment]
Fair enough. I'll look into it tomorrow and track down the best options. Thanks.

**Comment by mattrobenolt** [comment]
All `SENTRY_*` variables are internally stripped of `SENTRY_`, see: https://github.com/dcramer/sentry/blob/master/sentry/conf/settings.py#L23-25

There shouldn't be an instance where `SENTRY_URL_PREFIX` exists without `URL_PREFIX` existing unless you've manually overwritten somewhere.

What are you doing in your code to not have a `URL_PREFIX`?

**Comment by ghickman** [comment]
This is only true if you're using sentry as app inside a django project.

When installed as a system application the [runner](https://github.com/dcramer/sentry/blob/master/sentry/utils/runner.py#L90) specifies the [server settings](https://github.com/dcramer/sentry/blob/master/sentry/conf/server.py) file which doesn't contain the conversion code.

I could change the code to try `SENTRY_URL_PREFIX` first then `URL_PREFIX` next?

**Comment by mattrobenolt** [comment]
Do you mind sending me your project so I can reproduce? I don't feel comfortable changing this because no other plugin uses that convention. They all access `URL_PREFIX` directly. Maybe when using the runner, you're supposed to declare `URL_PREFIX` instead?

/cc @dcramer

**Comment by mattrobenolt** [comment]
I feel like, if anything, this could be an oversight in how Sentry handles loading different configs. One is being passed through the parser which converts `SENTRY_*` and the other isn't.

**Comment by dcramer** [comment]
Ya this is the same setting. You configure things using SENTRY_*, but they're not referenced that way internally.

**Comment by mattrobenolt** [comment]
Thanks for the confirmation. :)

@ghickman If there is still an issue with Sentry, you should file a bug there.

**Comment by dcramer** [comment]
Oh actually, the problem is this is importing Django settings, and it should be doing "from sentry.conf import settings"

**Comment by mattrobenolt** [comment]
Ahh. I see. Thanks. :)

**Pull request closed without merging**
